### ISSUE TITLE
--pjson when listing Workflows outputs invalid JSON document

### ISSUE THREAD

**Issue by soulscreme** [temporalio/tctl#133]
## Expected Behavior
`--pjson` should output well formatted JSON that can be parsed by standard parsers like `jq`.

## Actual Behavior
`--pjson` includes an extra comma at the end of the list that is out of spec and causes parser failures.

## Steps to Reproduce the Problem

  1. Execute listall for workflows.
  `tctl --namespace Money workflow listall --op --wt recurringVaultTransfer --pjson`
  2. Review output.
[
{"execution":{"workflowId":"2001-1000000011391-1","runId":"23c49786-0051-48cd-8268-2b3cdc19188a"},"type":{"name":"recurringVaultTransfer"},"startTime":"2021-12-14T18:49:32.074090Z","status":"Running","executionTime":"2021-12-14T18:49:32.074090Z","memo":{}},
]
  3. Attempt to parse with `jq` and receive error "parse error: Expected another array element at line 1, column 261"

## Specifications

  - Version: 1.10.5
  - Platform: Linux

**Comment by feedmeapples** [comment]
@soulscreme this has been addressed as part of this proposal https://github.com/temporalio/proposals/pull/26

The new UX of tctl will be handling piping json into jq and other tools work properly. Currently it's not the default behavior, later the new UX is going to be the default. See https://github.com/temporalio/tctl#trying-out-tctl-v1140-alpha-with-the-updated-ux

**Comment by feedmeapples** [comment]
quick update, `brew` now ships with the new beta UX that also improves on json output 

see https://github.com/temporalio/tctl#trying-out-new-tctl-v1170-beta-with-updated-ux

```
tctl config set version next

tctl w l --output json
```

**Comment by feedmeapples** [comment]
```
tctl -n canary w l --output json --limit 1
[
  {
    "close_time": "2022-04-11T19:58:01.31265Z",
    "execution": {
      "run_id": "f6f96bd6-71a1-4660-8553-b3c245175491",
      "workflow_id": "temporal.canary.cron-workflow.sanity-2022-04-11T15:57:57-04:00/workflow.standard-visibility"
    },
    "execution_time": "2022-04-11T19:57:57.156736Z",
    "history_length": 18,
    "memo": {},
    "start_time": "2022-04-11T19:57:57.156736Z",
    "status": 2,
    "type": {
      "name": "workflow.standard-visibility"
    }
  }
]
```

**Comment by feedmeapples** [comment]
closing as this is addressed with the new UX ^
