### ISSUE TITLE
TaskID range can't specified in admin list shard tasks command

### ISSUE THREAD

**Issue by yycptt** [temporalio/tctl#158]
Admin list tasks command only takes in min/max task visibility timestamp and [pass](https://github.com/temporalio/tctl/blob/main/cli_curr/adminCommands.go#L539) them to server for listing timer tasks.

For transfer/replication/visibility tasks, there's no flag for specifying the taskID range and min/max taskID field is also [not specified](https://github.com/temporalio/tctl/blob/main/cli_curr/adminCommands.go#L516) when calling admin list transfer/replication/visibility tasks API. This, I believe, means not task will be returned for those three task types.

**Comment by yycptt** [comment]
On server side, I will merge list transfer/timer/replication/visibility tasks API into one ListHistoryTasks API, which takes in the task category, [inclusive, exclusive) task key range (task key is a combination of task fire time and taskID), batch size and next page token. 

Once server side change is done, I will make the cli change as well.

Note: there'll be a behavior change for listing transfer/visibility/replication tasks as previously the taskID range is (exclusive, inclusive]. However, since the command is currently broken for those three task categories, we don't really need to worry about compatibility issues.

**Comment by feedmeapples** [comment]
closing as the PR is merged
