### ISSUE TITLE
tctl workflow show --output json outputs colors in some fields

### ISSUE THREAD

**Issue by bergundy** [temporalio/tctl#184]
Example:
```
...
  {
    "Details": "{\u001b[35mDetails\u001b[0m:[nil], Identity:tctl@macbearpig.local}",
    "ID": "125",
    "Time": "2022-04-19T23:21:36Z",
    "Type": "WorkflowExecutionTerminated"
  }
]
```

**Comment by feedmeapples** [comment]
moving the question from #232 

Would you like to have the default coloring (assuming it works properly)? or would prefer to just use jq if you want the coloring?

And yes piping into jq is also closer to unix philosophy. Interested more in a personal opinion here

**Comment by lorensr** [comment]
Prefer remove coloring

**Comment by bergundy** [comment]
I guess it depends on what happens when I copy the colored output straight from my terminal, do I get valid json? If that’s the case, the ideal for me would be to keep the colors unless output is a pipe.
If that’s too complex or unreliable, don’t color ever.
