### ISSUE TITLE
[Bug] Homebrew version mismatch

### ISSUE THREAD

**Issue by lorensr** [temporalio/tctl#266]
This seems weird to me:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/251288/188011568-3e863618-1b02-456c-ac05-a4448020ed28.png">

**Comment by feedmeapples** [comment]
When you opt-in into a newer UX for tctl by running `tctl config set version next`, `tctl -v` will start printing `1.17.0-alpha.2` as the version 

see https://github.com/temporalio/tctl/blob/e82d00ceeb9f7f14d86bf7158600fd2df1314d2e/cmd/tctl/main.go#L40 which switches the active version based on the value from config

**Comment by feedmeapples** [comment]
In the main branch the version was also updated to `tctl version 2.0.0-beta.1`

This is so people can opt-in and start playing with tctl v2
