### ISSUE TITLE
[Feature Request] Integrate batch operation APIs with Tctl tool

### ISSUE THREAD

**Issue by yux0** [temporalio/tctl#270]
### Is your feature request related to a problem? Please describe.

Four new APIs added in workflow service:
1. Start batch operation
2. Stop batch operation
3. Describe batch operation
4. List batch operation

Request integrate the tctl with the new batch APIs.

### Describe the solution you'd like

Only integrate the batch APIs in Tctl v2.

**Comment by feedmeapples** [comment]
done is v2
