### ISSUE TITLE
[Feature Request] Change `--query` to `--filter`

### ISSUE THREAD

**Issue by lorensr** [temporalio/tctl#273]
### Is your feature request related to a problem? Please describe.

`--query` might be confusing with Queries

https://docs.temporal.io/tctl/workflow/list/#--query

### Describe the solution you'd like

Change to `--filter`, since the argument is a List Filter

cc @flossypurse

**Comment by feedmeapples** [comment]
@lorensr @bergundy is this something that the SDK team and @flossypurse have agreed on?

**Comment by feedmeapples** [comment]
if so let's rename asap

**Comment by bergundy** [comment]
Seems reasonable to me.

**Comment by flossypurse** [comment]
Ya, good call out @lorensr

**Comment by feedmeapples** [comment]
Discussed with @bergundy, @alexshtin and @flossypurse 

As `--query` may also accept ORDER BY, renaming to `--filter` does not really communicate it well. Decided to leave as `--query`
