### ISSUE TITLE
[Bug] workflow list time filter error message

### ISSUE THREAD

**Issue by yiminc** [temporalio/tctl#84]
### Describe the bug

Using TCTL workflow list command with --et and --lt with time like '2021-09-08T10:30:00' does not work. 

### To Reproduce

Run command like:
$ tctl wf list --et '2021-09-08T10:30:00'
Error: Cannot parse time '2021-09-08T10:30:00', use UTC format '2006-01-02T15:04:05', time range or raw UnixNano directly. See help for more details.
Error Details: cannot parse timeRange 2021-09-08T10:30:00

Notice the error message suggest to use the same format as what was used.

However, if I use '2021-09-08T10:30:00Z' (notice the Z at the end), then it works.

**Comment by feedmeapples** [comment]
with https://github.com/temporalio/tctl/pull/197 the API now uses ListWorkflow API with a --query flag for filtering 
```
tctl w l -q 'StartTime > "2019-06-07T16:46:34-08:00"'
```
